vich_uploader:
    db_driver: orm

    mappings:
#        #TODO changer le nom products
#        file_image:
#            inject_on_load: true
#            uri_prefix: /images/files # 'l'URL de l'image
#            upload_destination: '%kernel.project_dir%/public/images/files'
